/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AssuranceLevelResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class AssuranceLevelResponse {
  @JsonProperty("assurance_level")
  private String assuranceLevel = null;

  @JsonProperty("provider")
  private String provider = null;

  @JsonProperty("serial_number")
  private String serialNumber = null;

  public AssuranceLevelResponse assuranceLevel(String assuranceLevel) {
    this.assuranceLevel = assuranceLevel;
    return this;
  }

   /**
   * A person&#x27;s assurance level. Valid values are &#x60;qualified&#x60;, &#x60;advanced&#x60; or &#x60;none&#x60;
   * @return assuranceLevel
  **/
  public String getAssuranceLevel() {
    return assuranceLevel;
  }

  public void setAssuranceLevel(String assuranceLevel) {
    this.assuranceLevel = assuranceLevel;
  }

  public AssuranceLevelResponse provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * The provider of the identity assurance.
   * @return provider
  **/
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public AssuranceLevelResponse serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * The serial number of the identity assurance.
   * @return serialNumber
  **/
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssuranceLevelResponse assuranceLevelResponse = (AssuranceLevelResponse) o;
    return Objects.equals(this.assuranceLevel, assuranceLevelResponse.assuranceLevel) &&
        Objects.equals(this.provider, assuranceLevelResponse.provider) &&
        Objects.equals(this.serialNumber, assuranceLevelResponse.serialNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assuranceLevel, provider, serialNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssuranceLevelResponse {\n");
    
    sb.append("    assuranceLevel: ").append(toIndentedString(assuranceLevel)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
