/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * Callback
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class Callback {
  @JsonProperty("signature_request_id")
  private UUID signatureRequestId = null;

  /**
   * The type of this callback (SUCCESS, UPDATE, ERROR).
   */
  public enum TypeEnum {
    SUCCESS("SUCCESS"),
    UPDATE("UPDATE"),
    ERROR("ERROR");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  /**
   * The status of this callback process (OPEN, COMPLETED, RESIGNATED).
   */
  public enum StateEnum {
    OPEN("OPEN"),
    COMPLETED("COMPLETED"),
    RESIGNATED("RESIGNATED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StateEnum fromValue(String input) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("state")
  private StateEnum state = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("attempts")
  private Integer attempts = null;

  @JsonProperty("messages")
  private List<String> messages = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("read_access")
  private List<String> readAccess = new ArrayList<>();

  @JsonProperty("write_access")
  private List<String> writeAccess = new ArrayList<>();

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("updated_at")
  private OffsetDateTime updatedAt = null;

  public Callback signatureRequestId(UUID signatureRequestId) {
    this.signatureRequestId = signatureRequestId;
    return this;
  }

   /**
   * Signature request&#x27;s unique ID on Skribble.
   * @return signatureRequestId
  **/
  public UUID getSignatureRequestId() {
    return signatureRequestId;
  }

  public void setSignatureRequestId(UUID signatureRequestId) {
    this.signatureRequestId = signatureRequestId;
  }

  public Callback type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The type of this callback (SUCCESS, UPDATE, ERROR).
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Callback state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * The status of this callback process (OPEN, COMPLETED, RESIGNATED).
   * @return state
  **/
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public Callback url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The called URL of this callback.
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Callback attempts(Integer attempts) {
    this.attempts = attempts;
    return this;
  }

   /**
   * The attempts this callback was carried out.
   * @return attempts
  **/
  public Integer getAttempts() {
    return attempts;
  }

  public void setAttempts(Integer attempts) {
    this.attempts = attempts;
  }

  public Callback messages(List<String> messages) {
    this.messages = messages;
    return this;
  }

  public Callback addMessagesItem(String messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Array of error messages in case that the callback failed
   * @return messages
  **/
  public List<String> getMessages() {
    return messages;
  }

  public void setMessages(List<String> messages) {
    this.messages = messages;
  }

  public Callback owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * E-mail address of the object owner.
   * @return owner
  **/
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public Callback readAccess(List<String> readAccess) {
    this.readAccess = readAccess;
    return this;
  }

  public Callback addReadAccessItem(String readAccessItem) {
    this.readAccess.add(readAccessItem);
    return this;
  }

   /**
   * E-mail addresses with read access to the object.
   * @return readAccess
  **/
  public List<String> getReadAccess() {
    return readAccess;
  }

  public void setReadAccess(List<String> readAccess) {
    this.readAccess = readAccess;
  }

  public Callback writeAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
    return this;
  }

  public Callback addWriteAccessItem(String writeAccessItem) {
    this.writeAccess.add(writeAccessItem);
    return this;
  }

   /**
   * E-mail addresses with write access to the object.
   * @return writeAccess
  **/
  public List<String> getWriteAccess() {
    return writeAccess;
  }

  public void setWriteAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
  }

  public Callback createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time at which the object was created.
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Callback updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The time at which the object was last changed.
   * @return updatedAt
  **/
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Callback callback = (Callback) o;
    return Objects.equals(this.signatureRequestId, callback.signatureRequestId) &&
        Objects.equals(this.type, callback.type) &&
        Objects.equals(this.state, callback.state) &&
        Objects.equals(this.url, callback.url) &&
        Objects.equals(this.attempts, callback.attempts) &&
        Objects.equals(this.messages, callback.messages) &&
        Objects.equals(this.owner, callback.owner) &&
        Objects.equals(this.readAccess, callback.readAccess) &&
        Objects.equals(this.writeAccess, callback.writeAccess) &&
        Objects.equals(this.createdAt, callback.createdAt) &&
        Objects.equals(this.updatedAt, callback.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signatureRequestId, type, state, url, attempts, messages, owner, readAccess, writeAccess, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Callback {\n");
    
    sb.append("    signatureRequestId: ").append(toIndentedString(signatureRequestId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    attempts: ").append(toIndentedString(attempts)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    readAccess: ").append(toIndentedString(readAccess)).append("\n");
    sb.append("    writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
