/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * CreateDocument
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class CreateDocument {
  @JsonProperty("title")
  private String title = null;

  /**
   * Content type of bytes sent in &#x60;content&#x60;. Currently, only &#x27;application/pdf&#x27; is supported. Must be used together with &#x60;content&#x60;.
   */
  public enum ContentTypeEnum {
    APPLICATION_PDF("APPLICATION/PDF");

    private String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ContentTypeEnum fromValue(String input) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("content_type")
  private ContentTypeEnum contentType = null;

  @JsonProperty("content")
  private String content = null;

  @JsonProperty("file_url")
  private String fileUrl = null;

  @JsonProperty("read_access")
  private List<String> readAccess = null;

  @JsonProperty("write_access")
  private List<String> writeAccess = null;

  public CreateDocument title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the document.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public CreateDocument contentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of bytes sent in &#x60;content&#x60;. Currently, only &#x27;application/pdf&#x27; is supported. Must be used together with &#x60;content&#x60;.
   * @return contentType
  **/
  public ContentTypeEnum getContentType() {
    return contentType;
  }

  public void setContentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
  }

  public CreateDocument content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Base64 encoded bytes of document. Must be used together with &#x60;content_type&#x60;.
   * @return content
  **/
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public CreateDocument fileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

   /**
   * Publicly accessible URL for document download. This parameter is incompatible with &#x60;content&#x60;+&#x60;content_type&#x60;.
   * @return fileUrl
  **/
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }

  public CreateDocument readAccess(List<String> readAccess) {
    this.readAccess = readAccess;
    return this;
  }

  public CreateDocument addReadAccessItem(String readAccessItem) {
    if (this.readAccess == null) {
      this.readAccess = new ArrayList<>();
    }
    this.readAccess.add(readAccessItem);
    return this;
  }

   /**
   * E-mail addresses with read access to the object.
   * @return readAccess
  **/
  public List<String> getReadAccess() {
    return readAccess;
  }

  public void setReadAccess(List<String> readAccess) {
    this.readAccess = readAccess;
  }

  public CreateDocument writeAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
    return this;
  }

  public CreateDocument addWriteAccessItem(String writeAccessItem) {
    if (this.writeAccess == null) {
      this.writeAccess = new ArrayList<>();
    }
    this.writeAccess.add(writeAccessItem);
    return this;
  }

   /**
   * E-mail addresses with write access to the object.
   * @return writeAccess
  **/
  public List<String> getWriteAccess() {
    return writeAccess;
  }

  public void setWriteAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDocument createDocument = (CreateDocument) o;
    return Objects.equals(this.title, createDocument.title) &&
        Objects.equals(this.contentType, createDocument.contentType) &&
        Objects.equals(this.content, createDocument.content) &&
        Objects.equals(this.fileUrl, createDocument.fileUrl) &&
        Objects.equals(this.readAccess, createDocument.readAccess) &&
        Objects.equals(this.writeAccess, createDocument.writeAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, contentType, content, fileUrl, readAccess, writeAccess);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDocument {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    readAccess: ").append(toIndentedString(readAccess)).append("\n");
    sb.append("    writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
