/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.SignerIdentityData;
import com.skribble.api.v2.client.VisualSignature;

/**
 * CreateSignature
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class CreateSignature {
  @JsonProperty("account_email")
  private String accountEmail = null;

  @JsonProperty("signer_identity_data")
  private SignerIdentityData signerIdentityData = null;

  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("sequence")
  private Integer sequence = null;

  @JsonProperty("notify")
  private Boolean notify = null;

  @JsonProperty("visual_signature")
  private VisualSignature visualSignature = null;

  @JsonProperty("language")
  private String language = null;

  public CreateSignature accountEmail(String accountEmail) {
    this.accountEmail = accountEmail;
    return this;
  }

   /**
   * Signer&#x27;s e-mail address.
   * @return accountEmail
  **/
  public String getAccountEmail() {
    return accountEmail;
  }

  public void setAccountEmail(String accountEmail) {
    this.accountEmail = accountEmail;
  }

  public CreateSignature signerIdentityData(SignerIdentityData signerIdentityData) {
    this.signerIdentityData = signerIdentityData;
    return this;
  }

   /**
   * Get signerIdentityData
   * @return signerIdentityData
  **/
  public SignerIdentityData getSignerIdentityData() {
    return signerIdentityData;
  }

  public void setSignerIdentityData(SignerIdentityData signerIdentityData) {
    this.signerIdentityData = signerIdentityData;
  }

  public CreateSignature order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Order can be used as custom field to implement a custom order functionality. For Skribble signing sequence use &#x27;sequence&#x27;.
   * @return order
  **/
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public CreateSignature sequence(Integer sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Sequence in which this signer will sign starting with &#x27;1&#x27;. If no order is supplied, participants can sign in any order. If the field contains a number, Skribble will enforce an ascending order defined by &#x60;sequence&#x60; in which the signers sign the document.
   * @return sequence
  **/
  public Integer getSequence() {
    return sequence;
  }

  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }

  public CreateSignature notify(Boolean notify) {
    this.notify = notify;
    return this;
  }

   /**
   * Send e-mails to notify the signer about this signature request and for all updates to it&#x27;s state. If set to &#x60;false&#x60;, no notifications will be sent by Skribble. Default is &#x60;true&#x60;
   * @return notify
  **/
  public Boolean isNotify() {
    return notify;
  }

  public void setNotify(Boolean notify) {
    this.notify = notify;
  }

  public CreateSignature visualSignature(VisualSignature visualSignature) {
    this.visualSignature = visualSignature;
    return this;
  }

   /**
   * Get visualSignature
   * @return visualSignature
  **/
  public VisualSignature getVisualSignature() {
    return visualSignature;
  }

  public void setVisualSignature(VisualSignature visualSignature) {
    this.visualSignature = visualSignature;
  }

  public CreateSignature language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Language of the email sent to the invitee
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSignature createSignature = (CreateSignature) o;
    return Objects.equals(this.accountEmail, createSignature.accountEmail) &&
        Objects.equals(this.signerIdentityData, createSignature.signerIdentityData) &&
        Objects.equals(this.order, createSignature.order) &&
        Objects.equals(this.sequence, createSignature.sequence) &&
        Objects.equals(this.notify, createSignature.notify) &&
        Objects.equals(this.visualSignature, createSignature.visualSignature) &&
        Objects.equals(this.language, createSignature.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountEmail, signerIdentityData, order, sequence, notify, visualSignature, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSignature {\n");
    
    sb.append("    accountEmail: ").append(toIndentedString(accountEmail)).append("\n");
    sb.append("    signerIdentityData: ").append(toIndentedString(signerIdentityData)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("    visualSignature: ").append(toIndentedString(visualSignature)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
