/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.CreateSignature;

import java.util.ArrayList;
import java.util.List;
/**
 * CreateSignatureRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class CreateSignatureRequest {
  @JsonProperty("title")
  private String title = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("content")
  private String content = null;

  /**
   * Content type of bytes sent in &#x60;content&#x60;. Currently, only &#x27;application/pdf&#x27; is supported. Must be used together with &#x60;content&#x60;. This parameter is incompatible with &#x60;file_url&#x60; and &#x60;document_id&#x60;.
   */
  public enum ContentTypeEnum {
    APPLICATION_PDF("APPLICATION/PDF");

    private String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ContentTypeEnum fromValue(String input) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("content_type")
  private ContentTypeEnum contentType = null;

  @JsonProperty("file_url")
  private String fileUrl = null;

  @JsonProperty("document_id")
  private String documentId = null;

  /**
   * Legislation of the signatures for this signature request. Default: ZERTES
   */
  public enum LegislationEnum {
    EIDAS("EIDAS"),
    ZERTES("ZERTES");

    private String value;

    LegislationEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LegislationEnum fromValue(String input) {
      for (LegislationEnum b : LegislationEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("legislation")
  private LegislationEnum legislation = null;

  /**
   * Minimal quality of the signatures for this signature request. Default: QES
   */
  public enum QualityEnum {
    AES("AES"),
    QES("QES"),
    DEMO("DEMO");

    private String value;

    QualityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static QualityEnum fromValue(String input) {
      for (QualityEnum b : QualityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("quality")
  private QualityEnum quality = null;

  @JsonProperty("signatures")
  private List<CreateSignature> signatures = null;

  @JsonProperty("cc_email_addresses")
  private List<String> ccEmailAddresses = null;

  @JsonProperty("callback_success_url")
  private String callbackSuccessUrl = null;

  @JsonProperty("callback_error_url")
  private String callbackErrorUrl = null;

  @JsonProperty("callback_update_url")
  private String callbackUpdateUrl = null;

  @JsonProperty("creator")
  private String creator = null;

  /**
   * Gets or Sets attachOnSuccess
   */
  public enum AttachOnSuccessEnum {
    SIGNED_DOCUMENT("SIGNED_DOCUMENT"),
    SIGNATURE_PROTOCOL("SIGNATURE_PROTOCOL");

    private String value;

    AttachOnSuccessEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AttachOnSuccessEnum fromValue(String input) {
      for (AttachOnSuccessEnum b : AttachOnSuccessEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("attach_on_success")
  private List<AttachOnSuccessEnum> attachOnSuccess = null;

  @JsonProperty("custom")
  private String custom = null;

  @JsonProperty("write_access")
  private List<String> writeAccess = null;

  public CreateSignatureRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the signature request.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public CreateSignatureRequest message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message sent to the other participants along with this signature request.
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public CreateSignatureRequest content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Base64 encoded bytes of document. Must be used together with &#x60;content_type&#x60;. This parameter is incompatible with &#x60;file_url&#x60; and &#x60;document_id&#x60;.
   * @return content
  **/
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public CreateSignatureRequest contentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of bytes sent in &#x60;content&#x60;. Currently, only &#x27;application/pdf&#x27; is supported. Must be used together with &#x60;content&#x60;. This parameter is incompatible with &#x60;file_url&#x60; and &#x60;document_id&#x60;.
   * @return contentType
  **/
  public ContentTypeEnum getContentType() {
    return contentType;
  }

  public void setContentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
  }

  public CreateSignatureRequest fileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

   /**
   * Publicly accessible URL for document download. This parameter is incompatible with &#x60;content&#x60;+&#x60;content_type&#x60; and &#x60;document_id&#x60;.
   * @return fileUrl
  **/
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }

  public CreateSignatureRequest documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Document ID of an existing document on Skribble. This parameter is incompatible with &#x60;content&#x60;+&#x60;content_type&#x60; and &#x60;file_url&#x60;.
   * @return documentId
  **/
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public CreateSignatureRequest legislation(LegislationEnum legislation) {
    this.legislation = legislation;
    return this;
  }

   /**
   * Legislation of the signatures for this signature request. Default: ZERTES
   * @return legislation
  **/
  public LegislationEnum getLegislation() {
    return legislation;
  }

  public void setLegislation(LegislationEnum legislation) {
    this.legislation = legislation;
  }

  public CreateSignatureRequest quality(QualityEnum quality) {
    this.quality = quality;
    return this;
  }

   /**
   * Minimal quality of the signatures for this signature request. Default: QES
   * @return quality
  **/
  public QualityEnum getQuality() {
    return quality;
  }

  public void setQuality(QualityEnum quality) {
    this.quality = quality;
  }

  public CreateSignatureRequest signatures(List<CreateSignature> signatures) {
    this.signatures = signatures;
    return this;
  }

  public CreateSignatureRequest addSignaturesItem(CreateSignature signaturesItem) {
    if (this.signatures == null) {
      this.signatures = new ArrayList<>();
    }
    this.signatures.add(signaturesItem);
    return this;
  }

   /**
   * Which signatures should be created within this signature request.
   * @return signatures
  **/
  public List<CreateSignature> getSignatures() {
    return signatures;
  }

  public void setSignatures(List<CreateSignature> signatures) {
    this.signatures = signatures;
  }

  public CreateSignatureRequest ccEmailAddresses(List<String> ccEmailAddresses) {
    this.ccEmailAddresses = ccEmailAddresses;
    return this;
  }

  public CreateSignatureRequest addCcEmailAddressesItem(String ccEmailAddressesItem) {
    if (this.ccEmailAddresses == null) {
      this.ccEmailAddresses = new ArrayList<>();
    }
    this.ccEmailAddresses.add(ccEmailAddressesItem);
    return this;
  }

   /**
   * CC e-mail addresses notifications are sent to.
   * @return ccEmailAddresses
  **/
  public List<String> getCcEmailAddresses() {
    return ccEmailAddresses;
  }

  public void setCcEmailAddresses(List<String> ccEmailAddresses) {
    this.ccEmailAddresses = ccEmailAddresses;
  }

  public CreateSignatureRequest callbackSuccessUrl(String callbackSuccessUrl) {
    this.callbackSuccessUrl = callbackSuccessUrl;
    return this;
  }

   /**
   * Callback-URL which is called on overall success. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values.
   * @return callbackSuccessUrl
  **/
  public String getCallbackSuccessUrl() {
    return callbackSuccessUrl;
  }

  public void setCallbackSuccessUrl(String callbackSuccessUrl) {
    this.callbackSuccessUrl = callbackSuccessUrl;
  }

  public CreateSignatureRequest callbackErrorUrl(String callbackErrorUrl) {
    this.callbackErrorUrl = callbackErrorUrl;
    return this;
  }

   /**
   * Callback-URL which is called in case of an error. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values.
   * @return callbackErrorUrl
  **/
  public String getCallbackErrorUrl() {
    return callbackErrorUrl;
  }

  public void setCallbackErrorUrl(String callbackErrorUrl) {
    this.callbackErrorUrl = callbackErrorUrl;
  }

  public CreateSignatureRequest callbackUpdateUrl(String callbackUpdateUrl) {
    this.callbackUpdateUrl = callbackUpdateUrl;
    return this;
  }

   /**
   * Callback-URL which is called in case of an update. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values.
   * @return callbackUpdateUrl
  **/
  public String getCallbackUpdateUrl() {
    return callbackUpdateUrl;
  }

  public void setCallbackUpdateUrl(String callbackUpdateUrl) {
    this.callbackUpdateUrl = callbackUpdateUrl;
  }

  public CreateSignatureRequest creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * The email of the user you want to impersonate on creating the signature request.
   * @return creator
  **/
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public CreateSignatureRequest attachOnSuccess(List<AttachOnSuccessEnum> attachOnSuccess) {
    this.attachOnSuccess = attachOnSuccess;
    return this;
  }

  public CreateSignatureRequest addAttachOnSuccessItem(AttachOnSuccessEnum attachOnSuccessItem) {
    if (this.attachOnSuccess == null) {
      this.attachOnSuccess = new ArrayList<>();
    }
    this.attachOnSuccess.add(attachOnSuccessItem);
    return this;
  }

   /**
   * Documents that will be attached additionally to the all-signatures-complete email.
   * @return attachOnSuccess
  **/
  public List<AttachOnSuccessEnum> getAttachOnSuccess() {
    return attachOnSuccess;
  }

  public void setAttachOnSuccess(List<AttachOnSuccessEnum> attachOnSuccess) {
    this.attachOnSuccess = attachOnSuccess;
  }

  public CreateSignatureRequest custom(String custom) {
    this.custom = custom;
    return this;
  }

   /**
   * Custom field where own/customer settings related to this signature request can be stored for future actions. The field is limited to a maximum of 10000 characters.
   * @return custom
  **/
  public String getCustom() {
    return custom;
  }

  public void setCustom(String custom) {
    this.custom = custom;
  }

  public CreateSignatureRequest writeAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
    return this;
  }

  public CreateSignatureRequest addWriteAccessItem(String writeAccessItem) {
    if (this.writeAccess == null) {
      this.writeAccess = new ArrayList<>();
    }
    this.writeAccess.add(writeAccessItem);
    return this;
  }

   /**
   * Give existing users full write access to this signature request.
   * @return writeAccess
  **/
  public List<String> getWriteAccess() {
    return writeAccess;
  }

  public void setWriteAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSignatureRequest createSignatureRequest = (CreateSignatureRequest) o;
    return Objects.equals(this.title, createSignatureRequest.title) &&
        Objects.equals(this.message, createSignatureRequest.message) &&
        Objects.equals(this.content, createSignatureRequest.content) &&
        Objects.equals(this.contentType, createSignatureRequest.contentType) &&
        Objects.equals(this.fileUrl, createSignatureRequest.fileUrl) &&
        Objects.equals(this.documentId, createSignatureRequest.documentId) &&
        Objects.equals(this.legislation, createSignatureRequest.legislation) &&
        Objects.equals(this.quality, createSignatureRequest.quality) &&
        Objects.equals(this.signatures, createSignatureRequest.signatures) &&
        Objects.equals(this.ccEmailAddresses, createSignatureRequest.ccEmailAddresses) &&
        Objects.equals(this.callbackSuccessUrl, createSignatureRequest.callbackSuccessUrl) &&
        Objects.equals(this.callbackErrorUrl, createSignatureRequest.callbackErrorUrl) &&
        Objects.equals(this.callbackUpdateUrl, createSignatureRequest.callbackUpdateUrl) &&
        Objects.equals(this.creator, createSignatureRequest.creator) &&
        Objects.equals(this.attachOnSuccess, createSignatureRequest.attachOnSuccess) &&
        Objects.equals(this.custom, createSignatureRequest.custom) &&
        Objects.equals(this.writeAccess, createSignatureRequest.writeAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, message, content, contentType, fileUrl, documentId, legislation, quality, signatures, ccEmailAddresses, callbackSuccessUrl, callbackErrorUrl, callbackUpdateUrl, creator, attachOnSuccess, custom, writeAccess);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSignatureRequest {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    legislation: ").append(toIndentedString(legislation)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    signatures: ").append(toIndentedString(signatures)).append("\n");
    sb.append("    ccEmailAddresses: ").append(toIndentedString(ccEmailAddresses)).append("\n");
    sb.append("    callbackSuccessUrl: ").append(toIndentedString(callbackSuccessUrl)).append("\n");
    sb.append("    callbackErrorUrl: ").append(toIndentedString(callbackErrorUrl)).append("\n");
    sb.append("    callbackUpdateUrl: ").append(toIndentedString(callbackUpdateUrl)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    attachOnSuccess: ").append(toIndentedString(attachOnSuccess)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
