/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.SignatureFieldInfo;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * Document
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class Document {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("parent_id")
  private String parentId = null;

  @JsonProperty("title")
  private String title = null;

  /**
   * Content type of document. Currently only &#x27;application/pdf&#x27; is supported.
   */
  public enum ContentTypeEnum {
    APPLICATION_PDF("APPLICATION/PDF");

    private String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ContentTypeEnum fromValue(String input) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("content_type")
  private ContentTypeEnum contentType = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("page_count")
  private Integer pageCount = null;

  @JsonProperty("page_width")
  private Integer pageWidth = null;

  @JsonProperty("page_height")
  private Integer pageHeight = null;

  @JsonProperty("signature_fields")
  private List<SignatureFieldInfo> signatureFields = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("read_access")
  private List<String> readAccess = new ArrayList<>();

  @JsonProperty("write_access")
  private List<String> writeAccess = new ArrayList<>();

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("updated_at")
  private OffsetDateTime updatedAt = null;

  public Document id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Document&#x27;s unique ID on Skribble.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Document parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * ID of document’s parent. Will not exist for the original document.
   * @return parentId
  **/
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public Document title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the document.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Document contentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of document. Currently only &#x27;application/pdf&#x27; is supported.
   * @return contentType
  **/
  public ContentTypeEnum getContentType() {
    return contentType;
  }

  public void setContentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
  }

  public Document size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Content size in bytes.
   * @return size
  **/
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public Document pageCount(Integer pageCount) {
    this.pageCount = pageCount;
    return this;
  }

   /**
   * Number of pages in the document.
   * @return pageCount
  **/
  public Integer getPageCount() {
    return pageCount;
  }

  public void setPageCount(Integer pageCount) {
    this.pageCount = pageCount;
  }

  public Document pageWidth(Integer pageWidth) {
    this.pageWidth = pageWidth;
    return this;
  }

   /**
   * Page width
   * @return pageWidth
  **/
  public Integer getPageWidth() {
    return pageWidth;
  }

  public void setPageWidth(Integer pageWidth) {
    this.pageWidth = pageWidth;
  }

  public Document pageHeight(Integer pageHeight) {
    this.pageHeight = pageHeight;
    return this;
  }

   /**
   * Page height
   * @return pageHeight
  **/
  public Integer getPageHeight() {
    return pageHeight;
  }

  public void setPageHeight(Integer pageHeight) {
    this.pageHeight = pageHeight;
  }

  public Document signatureFields(List<SignatureFieldInfo> signatureFields) {
    this.signatureFields = signatureFields;
    return this;
  }

  public Document addSignatureFieldsItem(SignatureFieldInfo signatureFieldsItem) {
    if (this.signatureFields == null) {
      this.signatureFields = new ArrayList<>();
    }
    this.signatureFields.add(signatureFieldsItem);
    return this;
  }

   /**
   * Signature fields
   * @return signatureFields
  **/
  public List<SignatureFieldInfo> getSignatureFields() {
    return signatureFields;
  }

  public void setSignatureFields(List<SignatureFieldInfo> signatureFields) {
    this.signatureFields = signatureFields;
  }

  public Document owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * E-mail address of the object owner.
   * @return owner
  **/
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public Document readAccess(List<String> readAccess) {
    this.readAccess = readAccess;
    return this;
  }

  public Document addReadAccessItem(String readAccessItem) {
    this.readAccess.add(readAccessItem);
    return this;
  }

   /**
   * E-mail addresses with read access to the object.
   * @return readAccess
  **/
  public List<String> getReadAccess() {
    return readAccess;
  }

  public void setReadAccess(List<String> readAccess) {
    this.readAccess = readAccess;
  }

  public Document writeAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
    return this;
  }

  public Document addWriteAccessItem(String writeAccessItem) {
    this.writeAccess.add(writeAccessItem);
    return this;
  }

   /**
   * E-mail addresses with write access to the object.
   * @return writeAccess
  **/
  public List<String> getWriteAccess() {
    return writeAccess;
  }

  public void setWriteAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
  }

  public Document createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time at which the object was created.
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Document updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The time at which the object was last changed.
   * @return updatedAt
  **/
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return Objects.equals(this.id, document.id) &&
        Objects.equals(this.parentId, document.parentId) &&
        Objects.equals(this.title, document.title) &&
        Objects.equals(this.contentType, document.contentType) &&
        Objects.equals(this.size, document.size) &&
        Objects.equals(this.pageCount, document.pageCount) &&
        Objects.equals(this.pageWidth, document.pageWidth) &&
        Objects.equals(this.pageHeight, document.pageHeight) &&
        Objects.equals(this.signatureFields, document.signatureFields) &&
        Objects.equals(this.owner, document.owner) &&
        Objects.equals(this.readAccess, document.readAccess) &&
        Objects.equals(this.writeAccess, document.writeAccess) &&
        Objects.equals(this.createdAt, document.createdAt) &&
        Objects.equals(this.updatedAt, document.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentId, title, contentType, size, pageCount, pageWidth, pageHeight, signatureFields, owner, readAccess, writeAccess, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    pageCount: ").append(toIndentedString(pageCount)).append("\n");
    sb.append("    pageWidth: ").append(toIndentedString(pageWidth)).append("\n");
    sb.append("    pageHeight: ").append(toIndentedString(pageHeight)).append("\n");
    sb.append("    signatureFields: ").append(toIndentedString(signatureFields)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    readAccess: ").append(toIndentedString(readAccess)).append("\n");
    sb.append("    writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
