/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines an image to be used inside a field.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class FieldImage {
  @JsonProperty("content_type")
  private String contentType = null;

  @JsonProperty("content")
  private String content = null;

  @JsonProperty("content_size")
  private Integer contentSize = null;

  public FieldImage contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of bytes sent in &#x60;content&#x60;. Must be used together with &#x60;content&#x60;.
   * @return contentType
  **/
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public FieldImage content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Base64 encoded bytes of content. Must be used together with &#x60;content_type&#x60;. The value is *Write Only*.
   * @return content
  **/
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public FieldImage contentSize(Integer contentSize) {
    this.contentSize = contentSize;
    return this;
  }

   /**
   * Size of &#x60;content&#x60; in bytes. Will be calculated by the storage system.
   * @return contentSize
  **/
  public Integer getContentSize() {
    return contentSize;
  }

  public void setContentSize(Integer contentSize) {
    this.contentSize = contentSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldImage fieldImage = (FieldImage) o;
    return Objects.equals(this.contentType, fieldImage.contentType) &&
        Objects.equals(this.content, fieldImage.content) &&
        Objects.equals(this.contentSize, fieldImage.contentSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentType, content, contentSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldImage {\n");
    
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    contentSize: ").append(toIndentedString(contentSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
