/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A position in the PDF coordinate system.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class Position {
  @JsonProperty("invisible")
  private Boolean invisible = null;

  @JsonProperty("x")
  private Float x = null;

  @JsonProperty("y")
  private Float y = null;

  @JsonProperty("width")
  private Float width = null;

  @JsonProperty("height")
  private Float height = null;

  @JsonProperty("page")
  private String page = null;

  @JsonProperty("rotation")
  private Integer rotation = null;

  public Position invisible(Boolean invisible) {
    this.invisible = invisible;
    return this;
  }

   /**
   * Get invisible
   * @return invisible
  **/
  public Boolean isInvisible() {
    return invisible;
  }

  public void setInvisible(Boolean invisible) {
    this.invisible = invisible;
  }

  public Position x(Float x) {
    this.x = x;
    return this;
  }

   /**
   * Get x
   * @return x
  **/
  public Float getX() {
    return x;
  }

  public void setX(Float x) {
    this.x = x;
  }

  public Position y(Float y) {
    this.y = y;
    return this;
  }

   /**
   * Get y
   * @return y
  **/
  public Float getY() {
    return y;
  }

  public void setY(Float y) {
    this.y = y;
  }

  public Position width(Float width) {
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  public Float getWidth() {
    return width;
  }

  public void setWidth(Float width) {
    this.width = width;
  }

  public Position height(Float height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  public Float getHeight() {
    return height;
  }

  public void setHeight(Float height) {
    this.height = height;
  }

  public Position page(String page) {
    this.page = page;
    return this;
  }

   /**
   * Page index starting at &#x27;0&#x27;.
   * @return page
  **/
  public String getPage() {
    return page;
  }

  public void setPage(String page) {
    this.page = page;
  }

  public Position rotation(Integer rotation) {
    this.rotation = rotation;
    return this;
  }

   /**
   * Defines a rotation of the field content. If used in context with a form field, then only the values 0, 90, 180, 270 are legal. Otherwise every value is legal. The rotation is applied counter clockwise. 
   * @return rotation
  **/
  public Integer getRotation() {
    return rotation;
  }

  public void setRotation(Integer rotation) {
    this.rotation = rotation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Position position = (Position) o;
    return Objects.equals(this.invisible, position.invisible) &&
        Objects.equals(this.x, position.x) &&
        Objects.equals(this.y, position.y) &&
        Objects.equals(this.width, position.width) &&
        Objects.equals(this.height, position.height) &&
        Objects.equals(this.page, position.page) &&
        Objects.equals(this.rotation, position.rotation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invisible, x, y, width, height, page, rotation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Position {\n");
    
    sb.append("    invisible: ").append(toIndentedString(invisible)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    rotation: ").append(toIndentedString(rotation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
