/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.VisualSignature;

/**
 * Seal
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class Seal {
  @JsonProperty("title")
  private String title = null;

  @JsonProperty("content")
  private String content = null;

  @JsonProperty("visual_signature")
  private VisualSignature visualSignature = null;

  @JsonProperty("account_name")
  private String accountName = null;

  public Seal title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the document, can be empty.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Seal content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Base64 encoded bytes of document.
   * @return content
  **/
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Seal visualSignature(VisualSignature visualSignature) {
    this.visualSignature = visualSignature;
    return this;
  }

   /**
   * Get visualSignature
   * @return visualSignature
  **/
  public VisualSignature getVisualSignature() {
    return visualSignature;
  }

  public void setVisualSignature(VisualSignature visualSignature) {
    this.visualSignature = visualSignature;
  }

  public Seal accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Account name of the seal contract that should be used.
   * @return accountName
  **/
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Seal seal = (Seal) o;
    return Objects.equals(this.title, seal.title) &&
        Objects.equals(this.content, seal.content) &&
        Objects.equals(this.visualSignature, seal.visualSignature) &&
        Objects.equals(this.accountName, seal.accountName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, content, visualSignature, accountName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Seal {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    visualSignature: ").append(toIndentedString(visualSignature)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
