/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.SignatureRequestAttachment;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * SignatureRequestobject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class SignatureRequestobject {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("document_id")
  private String documentId = null;

  /**
   * Legislation of the signatures for this signature request. Default: ZERTES
   */
  public enum LegislationEnum {
    EIDAS("EIDAS"),
    ZERTES("ZERTES");

    private String value;

    LegislationEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LegislationEnum fromValue(String input) {
      for (LegislationEnum b : LegislationEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("legislation")
  private LegislationEnum legislation = null;

  /**
   * Minimal quality of the signatures for this signature request. Default: QES
   */
  public enum QualityEnum {
    AES("AES"),
    QES("QES"),
    DEMO("DEMO");

    private String value;

    QualityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static QualityEnum fromValue(String input) {
      for (QualityEnum b : QualityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("quality")
  private QualityEnum quality = null;

  @JsonProperty("signing_url")
  private String signingUrl = null;

  /**
   * Signature request&#x27;s status based on all requested signature&#x27;s individual statuses.
   */
  public enum StatusOverallEnum {
    OPEN("OPEN"),
    WAITING("WAITING"),
    DECLINED("DECLINED"),
    WITHDRAWN("WITHDRAWN"),
    SIGNED("SIGNED"),
    UNDEFINED("UNDEFINED"),
    ERROR("ERROR");

    private String value;

    StatusOverallEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusOverallEnum fromValue(String input) {
      for (StatusOverallEnum b : StatusOverallEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status_overall")
  private StatusOverallEnum statusOverall = null;

  @JsonProperty("business")
  private String business = null;

  @JsonProperty("signatures")
  private List<Object> signatures = new ArrayList<>();

  @JsonProperty("cc_email_addresses")
  private List<String> ccEmailAddresses = null;

  @JsonProperty("expiration_date")
  private LocalDate expirationDate = null;

  /**
   * Gets or Sets attachOnSuccess
   */
  public enum AttachOnSuccessEnum {
    SIGNED_DOCUMENT("SIGNED_DOCUMENT"),
    SIGNATURE_PROTOCOL("SIGNATURE_PROTOCOL");

    private String value;

    AttachOnSuccessEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AttachOnSuccessEnum fromValue(String input) {
      for (AttachOnSuccessEnum b : AttachOnSuccessEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("attach_on_success")
  private List<AttachOnSuccessEnum> attachOnSuccess = null;

  @JsonProperty("callback_success_url")
  private String callbackSuccessUrl = null;

  @JsonProperty("callback_error_url")
  private String callbackErrorUrl = null;

  @JsonProperty("callback_update_url")
  private String callbackUpdateUrl = null;

  @JsonProperty("custom")
  private String custom = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("attachments")
  private List<SignatureRequestAttachment> attachments = null;

  @JsonProperty("read_access")
  private List<String> readAccess = new ArrayList<>();

  @JsonProperty("write_access")
  private List<String> writeAccess = new ArrayList<>();

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("updated_at")
  private OffsetDateTime updatedAt = null;

  public SignatureRequestobject id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Signature request&#x27;s unique ID on Skribble.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SignatureRequestobject title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the signature request.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SignatureRequestobject message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message sent to the other participants along with this signature request.
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public SignatureRequestobject documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * The document to sign.
   * @return documentId
  **/
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public SignatureRequestobject legislation(LegislationEnum legislation) {
    this.legislation = legislation;
    return this;
  }

   /**
   * Legislation of the signatures for this signature request. Default: ZERTES
   * @return legislation
  **/
  public LegislationEnum getLegislation() {
    return legislation;
  }

  public void setLegislation(LegislationEnum legislation) {
    this.legislation = legislation;
  }

  public SignatureRequestobject quality(QualityEnum quality) {
    this.quality = quality;
    return this;
  }

   /**
   * Minimal quality of the signatures for this signature request. Default: QES
   * @return quality
  **/
  public QualityEnum getQuality() {
    return quality;
  }

  public void setQuality(QualityEnum quality) {
    this.quality = quality;
  }

  public SignatureRequestobject signingUrl(String signingUrl) {
    this.signingUrl = signingUrl;
    return this;
  }

   /**
   * URL on Skribble&#x27;s platform where authorized users can view and sign the signature request.
   * @return signingUrl
  **/
  public String getSigningUrl() {
    return signingUrl;
  }

  public void setSigningUrl(String signingUrl) {
    this.signingUrl = signingUrl;
  }

  public SignatureRequestobject statusOverall(StatusOverallEnum statusOverall) {
    this.statusOverall = statusOverall;
    return this;
  }

   /**
   * Signature request&#x27;s status based on all requested signature&#x27;s individual statuses.
   * @return statusOverall
  **/
  public StatusOverallEnum getStatusOverall() {
    return statusOverall;
  }

  public void setStatusOverall(StatusOverallEnum statusOverall) {
    this.statusOverall = statusOverall;
  }

  public SignatureRequestobject business(String business) {
    this.business = business;
    return this;
  }

   /**
   * Business of signature request.
   * @return business
  **/
  public String getBusiness() {
    return business;
  }

  public void setBusiness(String business) {
    this.business = business;
  }

  public SignatureRequestobject signatures(List<Object> signatures) {
    this.signatures = signatures;
    return this;
  }

  public SignatureRequestobject addSignaturesItem(Object signaturesItem) {
    this.signatures.add(signaturesItem);
    return this;
  }

   /**
   * Requested signatures of this signature request.
   * @return signatures
  **/
  public List<Object> getSignatures() {
    return signatures;
  }

  public void setSignatures(List<Object> signatures) {
    this.signatures = signatures;
  }

  public SignatureRequestobject ccEmailAddresses(List<String> ccEmailAddresses) {
    this.ccEmailAddresses = ccEmailAddresses;
    return this;
  }

  public SignatureRequestobject addCcEmailAddressesItem(String ccEmailAddressesItem) {
    if (this.ccEmailAddresses == null) {
      this.ccEmailAddresses = new ArrayList<>();
    }
    this.ccEmailAddresses.add(ccEmailAddressesItem);
    return this;
  }

   /**
   * CC e-mail addresses notifications are sent to.
   * @return ccEmailAddresses
  **/
  public List<String> getCcEmailAddresses() {
    return ccEmailAddresses;
  }

  public void setCcEmailAddresses(List<String> ccEmailAddresses) {
    this.ccEmailAddresses = ccEmailAddresses;
  }

  public SignatureRequestobject expirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Expiration date of this signature request. Date scheduled at this time when automatic deletion will remove the signature request.
   * @return expirationDate
  **/
  public LocalDate getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
  }

  public SignatureRequestobject attachOnSuccess(List<AttachOnSuccessEnum> attachOnSuccess) {
    this.attachOnSuccess = attachOnSuccess;
    return this;
  }

  public SignatureRequestobject addAttachOnSuccessItem(AttachOnSuccessEnum attachOnSuccessItem) {
    if (this.attachOnSuccess == null) {
      this.attachOnSuccess = new ArrayList<>();
    }
    this.attachOnSuccess.add(attachOnSuccessItem);
    return this;
  }

   /**
   * Documents that will be attached additionally to the all-signatures-complete email.
   * @return attachOnSuccess
  **/
  public List<AttachOnSuccessEnum> getAttachOnSuccess() {
    return attachOnSuccess;
  }

  public void setAttachOnSuccess(List<AttachOnSuccessEnum> attachOnSuccess) {
    this.attachOnSuccess = attachOnSuccess;
  }

  public SignatureRequestobject callbackSuccessUrl(String callbackSuccessUrl) {
    this.callbackSuccessUrl = callbackSuccessUrl;
    return this;
  }

   /**
   * Callback-URL which is called on overall success. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values.
   * @return callbackSuccessUrl
  **/
  public String getCallbackSuccessUrl() {
    return callbackSuccessUrl;
  }

  public void setCallbackSuccessUrl(String callbackSuccessUrl) {
    this.callbackSuccessUrl = callbackSuccessUrl;
  }

  public SignatureRequestobject callbackErrorUrl(String callbackErrorUrl) {
    this.callbackErrorUrl = callbackErrorUrl;
    return this;
  }

   /**
   * Callback-URL which is called in case of an error. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values.
   * @return callbackErrorUrl
  **/
  public String getCallbackErrorUrl() {
    return callbackErrorUrl;
  }

  public void setCallbackErrorUrl(String callbackErrorUrl) {
    this.callbackErrorUrl = callbackErrorUrl;
  }

  public SignatureRequestobject callbackUpdateUrl(String callbackUpdateUrl) {
    this.callbackUpdateUrl = callbackUpdateUrl;
    return this;
  }

   /**
   * Callback-URL which is called in case of an update. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values.
   * @return callbackUpdateUrl
  **/
  public String getCallbackUpdateUrl() {
    return callbackUpdateUrl;
  }

  public void setCallbackUpdateUrl(String callbackUpdateUrl) {
    this.callbackUpdateUrl = callbackUpdateUrl;
  }

  public SignatureRequestobject custom(String custom) {
    this.custom = custom;
    return this;
  }

   /**
   * Custom field where own/customer settings related to this signature request can be stored for future actions. The field is limited to a maximum of 10000 characters.
   * @return custom
  **/
  public String getCustom() {
    return custom;
  }

  public void setCustom(String custom) {
    this.custom = custom;
  }

  public SignatureRequestobject owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * E-mail address of the object owner.
   * @return owner
  **/
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public SignatureRequestobject attachments(List<SignatureRequestAttachment> attachments) {
    this.attachments = attachments;
    return this;
  }

  public SignatureRequestobject addAttachmentsItem(SignatureRequestAttachment attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * File attachments to this signature request
   * @return attachments
  **/
  public List<SignatureRequestAttachment> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<SignatureRequestAttachment> attachments) {
    this.attachments = attachments;
  }

  public SignatureRequestobject readAccess(List<String> readAccess) {
    this.readAccess = readAccess;
    return this;
  }

  public SignatureRequestobject addReadAccessItem(String readAccessItem) {
    this.readAccess.add(readAccessItem);
    return this;
  }

   /**
   * E-mail addresses with read access to the object.
   * @return readAccess
  **/
  public List<String> getReadAccess() {
    return readAccess;
  }

  public void setReadAccess(List<String> readAccess) {
    this.readAccess = readAccess;
  }

  public SignatureRequestobject writeAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
    return this;
  }

  public SignatureRequestobject addWriteAccessItem(String writeAccessItem) {
    this.writeAccess.add(writeAccessItem);
    return this;
  }

   /**
   * E-mail addresses with write access to the object.
   * @return writeAccess
  **/
  public List<String> getWriteAccess() {
    return writeAccess;
  }

  public void setWriteAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
  }

  public SignatureRequestobject createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The time at which the object was created.
   * @return createdAt
  **/
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public SignatureRequestobject updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The time at which the object was last changed.
   * @return updatedAt
  **/
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureRequestobject signatureRequestobject = (SignatureRequestobject) o;
    return Objects.equals(this.id, signatureRequestobject.id) &&
        Objects.equals(this.title, signatureRequestobject.title) &&
        Objects.equals(this.message, signatureRequestobject.message) &&
        Objects.equals(this.documentId, signatureRequestobject.documentId) &&
        Objects.equals(this.legislation, signatureRequestobject.legislation) &&
        Objects.equals(this.quality, signatureRequestobject.quality) &&
        Objects.equals(this.signingUrl, signatureRequestobject.signingUrl) &&
        Objects.equals(this.statusOverall, signatureRequestobject.statusOverall) &&
        Objects.equals(this.business, signatureRequestobject.business) &&
        Objects.equals(this.signatures, signatureRequestobject.signatures) &&
        Objects.equals(this.ccEmailAddresses, signatureRequestobject.ccEmailAddresses) &&
        Objects.equals(this.expirationDate, signatureRequestobject.expirationDate) &&
        Objects.equals(this.attachOnSuccess, signatureRequestobject.attachOnSuccess) &&
        Objects.equals(this.callbackSuccessUrl, signatureRequestobject.callbackSuccessUrl) &&
        Objects.equals(this.callbackErrorUrl, signatureRequestobject.callbackErrorUrl) &&
        Objects.equals(this.callbackUpdateUrl, signatureRequestobject.callbackUpdateUrl) &&
        Objects.equals(this.custom, signatureRequestobject.custom) &&
        Objects.equals(this.owner, signatureRequestobject.owner) &&
        Objects.equals(this.attachments, signatureRequestobject.attachments) &&
        Objects.equals(this.readAccess, signatureRequestobject.readAccess) &&
        Objects.equals(this.writeAccess, signatureRequestobject.writeAccess) &&
        Objects.equals(this.createdAt, signatureRequestobject.createdAt) &&
        Objects.equals(this.updatedAt, signatureRequestobject.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, message, documentId, legislation, quality, signingUrl, statusOverall, business, signatures, ccEmailAddresses, expirationDate, attachOnSuccess, callbackSuccessUrl, callbackErrorUrl, callbackUpdateUrl, custom, owner, attachments, readAccess, writeAccess, createdAt, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureRequestobject {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    legislation: ").append(toIndentedString(legislation)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    signingUrl: ").append(toIndentedString(signingUrl)).append("\n");
    sb.append("    statusOverall: ").append(toIndentedString(statusOverall)).append("\n");
    sb.append("    business: ").append(toIndentedString(business)).append("\n");
    sb.append("    signatures: ").append(toIndentedString(signatures)).append("\n");
    sb.append("    ccEmailAddresses: ").append(toIndentedString(ccEmailAddresses)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    attachOnSuccess: ").append(toIndentedString(attachOnSuccess)).append("\n");
    sb.append("    callbackSuccessUrl: ").append(toIndentedString(callbackSuccessUrl)).append("\n");
    sb.append("    callbackErrorUrl: ").append(toIndentedString(callbackErrorUrl)).append("\n");
    sb.append("    callbackUpdateUrl: ").append(toIndentedString(callbackUpdateUrl)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    readAccess: ").append(toIndentedString(readAccess)).append("\n");
    sb.append("    writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
