/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.SignerIdentityData;
import com.skribble.api.v2.client.VisualSignature;

import java.time.OffsetDateTime;
/**
 * Signature
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class Signature {
  @JsonProperty("sid")
  private String sid = null;

  @JsonProperty("account_email")
  private String accountEmail = null;

  @JsonProperty("signer_identity_data")
  private SignerIdentityData signerIdentityData = null;

  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("sequence")
  private Integer sequence = null;

  /**
   * Current status of signature.
   */
  public enum StatusCodeEnum {
    OPEN("OPEN"),
    WAITING("WAITING"),
    DECLINED("DECLINED"),
    WITHDRAWN("WITHDRAWN"),
    SIGNED("SIGNED"),
    UNDEFINED("UNDEFINED"),
    ERROR("ERROR");

    private String value;

    StatusCodeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusCodeEnum fromValue(String input) {
      for (StatusCodeEnum b : StatusCodeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status_code")
  private StatusCodeEnum statusCode = null;

  @JsonProperty("notify")
  private Boolean notify = null;

  @JsonProperty("signing_url")
  private String signingUrl = null;

  @JsonProperty("decline_message")
  private String declineMessage = null;

  @JsonProperty("signed_at")
  private OffsetDateTime signedAt = null;

  /**
   * Time at which the signature was given.
   */
  public enum SignedLegislationEnum {
    UNDEFINED("UNDEFINED"),
    EIDAS("EIDAS"),
    ZERTES("ZERTES");

    private String value;

    SignedLegislationEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SignedLegislationEnum fromValue(String input) {
      for (SignedLegislationEnum b : SignedLegislationEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("signed_legislation")
  private SignedLegislationEnum signedLegislation = null;

  /**
   * Time at which the signature was given.
   */
  public enum SignedQualityEnum {
    QES("QES"),
    AES_MINIMAL("AES_MINIMAL"),
    AES("AES"),
    PART11("PART11"),
    SES("SES"),
    DEMO("DEMO");

    private String value;

    SignedQualityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SignedQualityEnum fromValue(String input) {
      for (SignedQualityEnum b : SignedQualityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("signed_quality")
  private SignedQualityEnum signedQuality = null;

  @JsonProperty("last_viewed_at")
  private OffsetDateTime lastViewedAt = null;

  @JsonProperty("visual_signature")
  private VisualSignature visualSignature = null;

  @JsonProperty("language")
  private String language = null;

  public Signature sid(String sid) {
    this.sid = sid;
    return this;
  }

   /**
   * ID of this signature
   * @return sid
  **/
  public String getSid() {
    return sid;
  }

  public void setSid(String sid) {
    this.sid = sid;
  }

  public Signature accountEmail(String accountEmail) {
    this.accountEmail = accountEmail;
    return this;
  }

   /**
   * Signer&#x27;s e-mail address.
   * @return accountEmail
  **/
  public String getAccountEmail() {
    return accountEmail;
  }

  public void setAccountEmail(String accountEmail) {
    this.accountEmail = accountEmail;
  }

  public Signature signerIdentityData(SignerIdentityData signerIdentityData) {
    this.signerIdentityData = signerIdentityData;
    return this;
  }

   /**
   * Get signerIdentityData
   * @return signerIdentityData
  **/
  public SignerIdentityData getSignerIdentityData() {
    return signerIdentityData;
  }

  public void setSignerIdentityData(SignerIdentityData signerIdentityData) {
    this.signerIdentityData = signerIdentityData;
  }

  public Signature order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Order can be used as custom field to implement a custom order functionality. For Skribble signing sequence use &#x27;sequence&#x27;.
   * @return order
  **/
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public Signature sequence(Integer sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Sequence in which this signer will sign starting with &#x27;1&#x27;. If no order is supplied, participants can sign in any order. If the field contains a number, Skribble will enforce an ascending order defined by &#x60;sequence&#x60; in which the signers sign the document.
   * @return sequence
  **/
  public Integer getSequence() {
    return sequence;
  }

  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }

  public Signature statusCode(StatusCodeEnum statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Current status of signature.
   * @return statusCode
  **/
  public StatusCodeEnum getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(StatusCodeEnum statusCode) {
    this.statusCode = statusCode;
  }

  public Signature notify(Boolean notify) {
    this.notify = notify;
    return this;
  }

   /**
   * Send e-mails to notify the signer about this signature request and for all updates to it&#x27;s state. If set to &#x60;false&#x60;, no notifications will be sent by Skribble. Default is &#x60;true&#x60;
   * @return notify
  **/
  public Boolean isNotify() {
    return notify;
  }

  public void setNotify(Boolean notify) {
    this.notify = notify;
  }

  public Signature signingUrl(String signingUrl) {
    this.signingUrl = signingUrl;
    return this;
  }

   /**
   * Get signingUrl
   * @return signingUrl
  **/
  public String getSigningUrl() {
    return signingUrl;
  }

  public void setSigningUrl(String signingUrl) {
    this.signingUrl = signingUrl;
  }

  public Signature declineMessage(String declineMessage) {
    this.declineMessage = declineMessage;
    return this;
  }

   /**
   * Decline message from the signature decliner.
   * @return declineMessage
  **/
  public String getDeclineMessage() {
    return declineMessage;
  }

  public void setDeclineMessage(String declineMessage) {
    this.declineMessage = declineMessage;
  }

  public Signature signedAt(OffsetDateTime signedAt) {
    this.signedAt = signedAt;
    return this;
  }

   /**
   * Time at which the signature was given.
   * @return signedAt
  **/
  public OffsetDateTime getSignedAt() {
    return signedAt;
  }

  public void setSignedAt(OffsetDateTime signedAt) {
    this.signedAt = signedAt;
  }

  public Signature signedLegislation(SignedLegislationEnum signedLegislation) {
    this.signedLegislation = signedLegislation;
    return this;
  }

   /**
   * Time at which the signature was given.
   * @return signedLegislation
  **/
  public SignedLegislationEnum getSignedLegislation() {
    return signedLegislation;
  }

  public void setSignedLegislation(SignedLegislationEnum signedLegislation) {
    this.signedLegislation = signedLegislation;
  }

  public Signature signedQuality(SignedQualityEnum signedQuality) {
    this.signedQuality = signedQuality;
    return this;
  }

   /**
   * Time at which the signature was given.
   * @return signedQuality
  **/
  public SignedQualityEnum getSignedQuality() {
    return signedQuality;
  }

  public void setSignedQuality(SignedQualityEnum signedQuality) {
    this.signedQuality = signedQuality;
  }

  public Signature lastViewedAt(OffsetDateTime lastViewedAt) {
    this.lastViewedAt = lastViewedAt;
    return this;
  }

   /**
   * The time at which the document was last opened in Skribble&#x27;s viewer.
   * @return lastViewedAt
  **/
  public OffsetDateTime getLastViewedAt() {
    return lastViewedAt;
  }

  public void setLastViewedAt(OffsetDateTime lastViewedAt) {
    this.lastViewedAt = lastViewedAt;
  }

  public Signature visualSignature(VisualSignature visualSignature) {
    this.visualSignature = visualSignature;
    return this;
  }

   /**
   * Get visualSignature
   * @return visualSignature
  **/
  public VisualSignature getVisualSignature() {
    return visualSignature;
  }

  public void setVisualSignature(VisualSignature visualSignature) {
    this.visualSignature = visualSignature;
  }

  public Signature language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Language of the invitation email.
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Signature signature = (Signature) o;
    return Objects.equals(this.sid, signature.sid) &&
        Objects.equals(this.accountEmail, signature.accountEmail) &&
        Objects.equals(this.signerIdentityData, signature.signerIdentityData) &&
        Objects.equals(this.order, signature.order) &&
        Objects.equals(this.sequence, signature.sequence) &&
        Objects.equals(this.statusCode, signature.statusCode) &&
        Objects.equals(this.notify, signature.notify) &&
        Objects.equals(this.signingUrl, signature.signingUrl) &&
        Objects.equals(this.declineMessage, signature.declineMessage) &&
        Objects.equals(this.signedAt, signature.signedAt) &&
        Objects.equals(this.signedLegislation, signature.signedLegislation) &&
        Objects.equals(this.signedQuality, signature.signedQuality) &&
        Objects.equals(this.lastViewedAt, signature.lastViewedAt) &&
        Objects.equals(this.visualSignature, signature.visualSignature) &&
        Objects.equals(this.language, signature.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sid, accountEmail, signerIdentityData, order, sequence, statusCode, notify, signingUrl, declineMessage, signedAt, signedLegislation, signedQuality, lastViewedAt, visualSignature, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Signature {\n");
    
    sb.append("    sid: ").append(toIndentedString(sid)).append("\n");
    sb.append("    accountEmail: ").append(toIndentedString(accountEmail)).append("\n");
    sb.append("    signerIdentityData: ").append(toIndentedString(signerIdentityData)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("    signingUrl: ").append(toIndentedString(signingUrl)).append("\n");
    sb.append("    declineMessage: ").append(toIndentedString(declineMessage)).append("\n");
    sb.append("    signedAt: ").append(toIndentedString(signedAt)).append("\n");
    sb.append("    signedLegislation: ").append(toIndentedString(signedLegislation)).append("\n");
    sb.append("    signedQuality: ").append(toIndentedString(signedQuality)).append("\n");
    sb.append("    lastViewedAt: ").append(toIndentedString(lastViewedAt)).append("\n");
    sb.append("    visualSignature: ").append(toIndentedString(visualSignature)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
