/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.CreateSignature;

import java.util.ArrayList;
import java.util.List;
/**
 * Update an existing &#x60;SignatureRequest&#x60;. Send only the fields, which shall be updated.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class UpdateSignatureRequest {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("message")
  private String message = null;

  /**
   * Legislation of the signatures for this signature request. Default: ZERTES
   */
  public enum LegislationEnum {
    EIDAS("EIDAS"),
    ZERTES("ZERTES");

    private String value;

    LegislationEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static LegislationEnum fromValue(String input) {
      for (LegislationEnum b : LegislationEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("legislation")
  private LegislationEnum legislation = null;

  /**
   * Minimal quality of the signatures for this signature request. Default: QES
   */
  public enum QualityEnum {
    AES("AES"),
    QES("QES"),
    DEMO("DEMO");

    private String value;

    QualityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static QualityEnum fromValue(String input) {
      for (QualityEnum b : QualityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("quality")
  private QualityEnum quality = null;

  @JsonProperty("signatures")
  private List<CreateSignature> signatures = null;

  @JsonProperty("cc_email_addresses")
  private List<String> ccEmailAddresses = null;

  @JsonProperty("callback_success_url")
  private String callbackSuccessUrl = null;

  @JsonProperty("callback_error_url")
  private String callbackErrorUrl = null;

  @JsonProperty("callback_update_url")
  private String callbackUpdateUrl = null;

  /**
   * Gets or Sets attachOnSuccess
   */
  public enum AttachOnSuccessEnum {
    SIGNED_DOCUMENT("SIGNED_DOCUMENT"),
    SIGNATURE_PROTOCOL("SIGNATURE_PROTOCOL");

    private String value;

    AttachOnSuccessEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AttachOnSuccessEnum fromValue(String input) {
      for (AttachOnSuccessEnum b : AttachOnSuccessEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("attach_on_success")
  private List<AttachOnSuccessEnum> attachOnSuccess = null;

  @JsonProperty("write_access")
  private List<String> writeAccess = null;

  public UpdateSignatureRequest id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Signature request&#x27;s unique ID on Skribble.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UpdateSignatureRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the signature request. Need &#x60;UPDATE&#x60; right to change.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public UpdateSignatureRequest message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message sent to the other participants along with this signature request. Need &#x60;UPDATE&#x60; right to change.
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public UpdateSignatureRequest legislation(LegislationEnum legislation) {
    this.legislation = legislation;
    return this;
  }

   /**
   * Legislation of the signatures for this signature request. Default: ZERTES
   * @return legislation
  **/
  public LegislationEnum getLegislation() {
    return legislation;
  }

  public void setLegislation(LegislationEnum legislation) {
    this.legislation = legislation;
  }

  public UpdateSignatureRequest quality(QualityEnum quality) {
    this.quality = quality;
    return this;
  }

   /**
   * Minimal quality of the signatures for this signature request. Default: QES
   * @return quality
  **/
  public QualityEnum getQuality() {
    return quality;
  }

  public void setQuality(QualityEnum quality) {
    this.quality = quality;
  }

  public UpdateSignatureRequest signatures(List<CreateSignature> signatures) {
    this.signatures = signatures;
    return this;
  }

  public UpdateSignatureRequest addSignaturesItem(CreateSignature signaturesItem) {
    if (this.signatures == null) {
      this.signatures = new ArrayList<>();
    }
    this.signatures.add(signaturesItem);
    return this;
  }

   /**
   * Which signatures should be created within this signature request. Need &#x60;MODIFY_SIGNERS&#x60; right to change.
   * @return signatures
  **/
  public List<CreateSignature> getSignatures() {
    return signatures;
  }

  public void setSignatures(List<CreateSignature> signatures) {
    this.signatures = signatures;
  }

  public UpdateSignatureRequest ccEmailAddresses(List<String> ccEmailAddresses) {
    this.ccEmailAddresses = ccEmailAddresses;
    return this;
  }

  public UpdateSignatureRequest addCcEmailAddressesItem(String ccEmailAddressesItem) {
    if (this.ccEmailAddresses == null) {
      this.ccEmailAddresses = new ArrayList<>();
    }
    this.ccEmailAddresses.add(ccEmailAddressesItem);
    return this;
  }

   /**
   * CC e-mail addresses notifications are sent to. Need &#x60;MODIFY_ACCESS&#x60; right to change.
   * @return ccEmailAddresses
  **/
  public List<String> getCcEmailAddresses() {
    return ccEmailAddresses;
  }

  public void setCcEmailAddresses(List<String> ccEmailAddresses) {
    this.ccEmailAddresses = ccEmailAddresses;
  }

  public UpdateSignatureRequest callbackSuccessUrl(String callbackSuccessUrl) {
    this.callbackSuccessUrl = callbackSuccessUrl;
    return this;
  }

   /**
   * Callback-URL which is called on overall success. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values. Need &#x60;UPDATE&#x60; right to change.
   * @return callbackSuccessUrl
  **/
  public String getCallbackSuccessUrl() {
    return callbackSuccessUrl;
  }

  public void setCallbackSuccessUrl(String callbackSuccessUrl) {
    this.callbackSuccessUrl = callbackSuccessUrl;
  }

  public UpdateSignatureRequest callbackErrorUrl(String callbackErrorUrl) {
    this.callbackErrorUrl = callbackErrorUrl;
    return this;
  }

   /**
   * Callback-URL which is called in case of an error. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values. Need &#x60;UPDATE&#x60; right to change.
   * @return callbackErrorUrl
  **/
  public String getCallbackErrorUrl() {
    return callbackErrorUrl;
  }

  public void setCallbackErrorUrl(String callbackErrorUrl) {
    this.callbackErrorUrl = callbackErrorUrl;
  }

  public UpdateSignatureRequest callbackUpdateUrl(String callbackUpdateUrl) {
    this.callbackUpdateUrl = callbackUpdateUrl;
    return this;
  }

   /**
   * Callback-URL which is called in case of an update. There are two template variables: SKRIBBLE_DOCUMENT_ID and SKRIBBLE_SIGNATURE_REQUEST_ID. Both are replaced before the callback by with their current values. Need &#x60;UPDATE&#x60; right to change.
   * @return callbackUpdateUrl
  **/
  public String getCallbackUpdateUrl() {
    return callbackUpdateUrl;
  }

  public void setCallbackUpdateUrl(String callbackUpdateUrl) {
    this.callbackUpdateUrl = callbackUpdateUrl;
  }

  public UpdateSignatureRequest attachOnSuccess(List<AttachOnSuccessEnum> attachOnSuccess) {
    this.attachOnSuccess = attachOnSuccess;
    return this;
  }

  public UpdateSignatureRequest addAttachOnSuccessItem(AttachOnSuccessEnum attachOnSuccessItem) {
    if (this.attachOnSuccess == null) {
      this.attachOnSuccess = new ArrayList<>();
    }
    this.attachOnSuccess.add(attachOnSuccessItem);
    return this;
  }

   /**
   * Documents that will be attached additionally to the all-signatures-complete email.
   * @return attachOnSuccess
  **/
  public List<AttachOnSuccessEnum> getAttachOnSuccess() {
    return attachOnSuccess;
  }

  public void setAttachOnSuccess(List<AttachOnSuccessEnum> attachOnSuccess) {
    this.attachOnSuccess = attachOnSuccess;
  }

  public UpdateSignatureRequest writeAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
    return this;
  }

  public UpdateSignatureRequest addWriteAccessItem(String writeAccessItem) {
    if (this.writeAccess == null) {
      this.writeAccess = new ArrayList<>();
    }
    this.writeAccess.add(writeAccessItem);
    return this;
  }

   /**
   * E-mail addresses with write access to the object. Need &#x60;MODIFY_ACCESS&#x60; right to change.
   * @return writeAccess
  **/
  public List<String> getWriteAccess() {
    return writeAccess;
  }

  public void setWriteAccess(List<String> writeAccess) {
    this.writeAccess = writeAccess;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSignatureRequest updateSignatureRequest = (UpdateSignatureRequest) o;
    return Objects.equals(this.id, updateSignatureRequest.id) &&
        Objects.equals(this.title, updateSignatureRequest.title) &&
        Objects.equals(this.message, updateSignatureRequest.message) &&
        Objects.equals(this.legislation, updateSignatureRequest.legislation) &&
        Objects.equals(this.quality, updateSignatureRequest.quality) &&
        Objects.equals(this.signatures, updateSignatureRequest.signatures) &&
        Objects.equals(this.ccEmailAddresses, updateSignatureRequest.ccEmailAddresses) &&
        Objects.equals(this.callbackSuccessUrl, updateSignatureRequest.callbackSuccessUrl) &&
        Objects.equals(this.callbackErrorUrl, updateSignatureRequest.callbackErrorUrl) &&
        Objects.equals(this.callbackUpdateUrl, updateSignatureRequest.callbackUpdateUrl) &&
        Objects.equals(this.attachOnSuccess, updateSignatureRequest.attachOnSuccess) &&
        Objects.equals(this.writeAccess, updateSignatureRequest.writeAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, message, legislation, quality, signatures, ccEmailAddresses, callbackSuccessUrl, callbackErrorUrl, callbackUpdateUrl, attachOnSuccess, writeAccess);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSignatureRequest {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    legislation: ").append(toIndentedString(legislation)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    signatures: ").append(toIndentedString(signatures)).append("\n");
    sb.append("    ccEmailAddresses: ").append(toIndentedString(ccEmailAddresses)).append("\n");
    sb.append("    callbackSuccessUrl: ").append(toIndentedString(callbackSuccessUrl)).append("\n");
    sb.append("    callbackErrorUrl: ").append(toIndentedString(callbackErrorUrl)).append("\n");
    sb.append("    callbackUpdateUrl: ").append(toIndentedString(callbackUpdateUrl)).append("\n");
    sb.append("    attachOnSuccess: ").append(toIndentedString(attachOnSuccess)).append("\n");
    sb.append("    writeAccess: ").append(toIndentedString(writeAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
