/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UserSignatureQualityQes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class UserSignatureQualityQes {
  @JsonProperty("zertes")
  private String zertes = null;

  @JsonProperty("eidas")
  private String eidas = null;

  public UserSignatureQualityQes zertes(String zertes) {
    this.zertes = zertes;
    return this;
  }

   /**
   * SR quality: QES / ZERTES
   * @return zertes
  **/
  public String getZertes() {
    return zertes;
  }

  public void setZertes(String zertes) {
    this.zertes = zertes;
  }

  public UserSignatureQualityQes eidas(String eidas) {
    this.eidas = eidas;
    return this;
  }

   /**
   * SR quality: QES / EIDAS
   * @return eidas
  **/
  public String getEidas() {
    return eidas;
  }

  public void setEidas(String eidas) {
    this.eidas = eidas;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSignatureQualityQes userSignatureQualityQes = (UserSignatureQualityQes) o;
    return Objects.equals(this.zertes, userSignatureQualityQes.zertes) &&
        Objects.equals(this.eidas, userSignatureQualityQes.eidas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(zertes, eidas);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSignatureQualityQes {\n");
    
    sb.append("    zertes: ").append(toIndentedString(zertes)).append("\n");
    sb.append("    eidas: ").append(toIndentedString(eidas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
