/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.UserSignatureQualityAes;
import com.skribble.api.v2.client.UserSignatureQualityAesMinimal;
import com.skribble.api.v2.client.UserSignatureQualityQes;
import com.skribble.api.v2.client.UserSignatureQualitySes;

/**
 * UserSignatureQualities
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class UserSignatureQualities {
  @JsonProperty("qes")
  private UserSignatureQualityQes qes = null;

  @JsonProperty("aes_minimal")
  private UserSignatureQualityAesMinimal aesMinimal = null;

  @JsonProperty("aes")
  private UserSignatureQualityAes aes = null;

  @JsonProperty("ses")
  private UserSignatureQualitySes ses = null;

  public UserSignatureQualities qes(UserSignatureQualityQes qes) {
    this.qes = qes;
    return this;
  }

   /**
   * Get qes
   * @return qes
  **/
  public UserSignatureQualityQes getQes() {
    return qes;
  }

  public void setQes(UserSignatureQualityQes qes) {
    this.qes = qes;
  }

  public UserSignatureQualities aesMinimal(UserSignatureQualityAesMinimal aesMinimal) {
    this.aesMinimal = aesMinimal;
    return this;
  }

   /**
   * Get aesMinimal
   * @return aesMinimal
  **/
  public UserSignatureQualityAesMinimal getAesMinimal() {
    return aesMinimal;
  }

  public void setAesMinimal(UserSignatureQualityAesMinimal aesMinimal) {
    this.aesMinimal = aesMinimal;
  }

  public UserSignatureQualities aes(UserSignatureQualityAes aes) {
    this.aes = aes;
    return this;
  }

   /**
   * Get aes
   * @return aes
  **/
  public UserSignatureQualityAes getAes() {
    return aes;
  }

  public void setAes(UserSignatureQualityAes aes) {
    this.aes = aes;
  }

  public UserSignatureQualities ses(UserSignatureQualitySes ses) {
    this.ses = ses;
    return this;
  }

   /**
   * Get ses
   * @return ses
  **/
  public UserSignatureQualitySes getSes() {
    return ses;
  }

  public void setSes(UserSignatureQualitySes ses) {
    this.ses = ses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSignatureQualities userSignatureQualities = (UserSignatureQualities) o;
    return Objects.equals(this.qes, userSignatureQualities.qes) &&
        Objects.equals(this.aesMinimal, userSignatureQualities.aesMinimal) &&
        Objects.equals(this.aes, userSignatureQualities.aes) &&
        Objects.equals(this.ses, userSignatureQualities.ses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qes, aesMinimal, aes, ses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSignatureQualities {\n");
    
    sb.append("    qes: ").append(toIndentedString(qes)).append("\n");
    sb.append("    aesMinimal: ").append(toIndentedString(aesMinimal)).append("\n");
    sb.append("    aes: ").append(toIndentedString(aes)).append("\n");
    sb.append("    ses: ").append(toIndentedString(ses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
