/*
 * 
 * All requests to the Skribble API must be authorized. To obtain an access token, please use the <b>/access/login</b> resource. Then add the access token as a HTTP header like:<br><code>Authorization: Bearer &lt;token></code>
 *
 * OpenAPI spec version: 2.0
 * Contact: info@skribble.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.skribble.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.skribble.api.v2.client.FieldImage;
import com.skribble.api.v2.client.Position;

import java.util.ArrayList;
import java.util.List;
/**
 * Defines the appearance of a signature in a document. If no appearance is defined, the signature will be invisible, which is a valid option.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-26T13:56:34.812195500+02:00[Europe/Zurich]")
public class VisualSignature {
  @JsonProperty("form_field")
  private String formField = null;

  @JsonProperty("position")
  private Position position = null;

  @JsonProperty("positions")
  private List<Position> positions = null;

  @JsonProperty("image")
  private FieldImage image = null;

  public VisualSignature formField(String formField) {
    this.formField = formField;
    return this;
  }

   /**
   * Name of the document’s form field in which the signature is placed. Takes precedence before &#x60;position&#x60;.
   * @return formField
  **/
  public String getFormField() {
    return formField;
  }

  public void setFormField(String formField) {
    this.formField = formField;
  }

  public VisualSignature position(Position position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  public Position getPosition() {
    return position;
  }

  public void setPosition(Position position) {
    this.position = position;
  }

  public VisualSignature positions(List<Position> positions) {
    this.positions = positions;
    return this;
  }

  public VisualSignature addPositionsItem(Position positionsItem) {
    if (this.positions == null) {
      this.positions = new ArrayList<>();
    }
    this.positions.add(positionsItem);
    return this;
  }

   /**
   * List of positions in the PDF coordinate system where the visual signatures will be placed.
   * @return positions
  **/
  public List<Position> getPositions() {
    return positions;
  }

  public void setPositions(List<Position> positions) {
    this.positions = positions;
  }

  public VisualSignature image(FieldImage image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  public FieldImage getImage() {
    return image;
  }

  public void setImage(FieldImage image) {
    this.image = image;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VisualSignature visualSignature = (VisualSignature) o;
    return Objects.equals(this.formField, visualSignature.formField) &&
        Objects.equals(this.position, visualSignature.position) &&
        Objects.equals(this.positions, visualSignature.positions) &&
        Objects.equals(this.image, visualSignature.image);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formField, position, positions, image);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VisualSignature {\n");
    
    sb.append("    formField: ").append(toIndentedString(formField)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
