name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v6
    secrets:
      mvnArgs: -Dskribble.username=${{secrets.USERNAME}} -Dskribble.authKey=${{secrets.AUTHKEY}}
