name: E2E-Build

on:
  schedule:
    - cron:  '0 1 * * 1'
  workflow_dispatch:
  
permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Dskribble.username=${{secrets.USERNAME}} -Dskribble.authKey=${{secrets.AUTHKEY}} -DtestEnvironment=E2E

